window.CASSIE_ARTICLES = [
  {
    id: "capture",
    cat: "build",
    title: ["为什么我做 Cassie Capture", "Why I built Cassie Capture"],
    meta: ["BUILD LOG · 已扩写", "BUILD LOG · EXPANDED"],
    deck: ["长文档不应该消失在滚动条里。", "Long documents should not vanish inside a scrollbar."],
    body: [[
      "我经常需要保存很长的网页文档。课程笔记、飞书文档、Google Docs，三四百页的那种。普通截图工具在几十页以内都很好，一旦超过一百页，要么浏览器崩掉，要么最后导出的 PDF 有一半是空白。",
      "我一开始以为这只是一个截图问题。后来才发现，真正的问题是内存：如果把三百页未压缩图像一直留在浏览器里，二三 GB 很快就没有了。于是 Cassie Capture 有了一个很简单、也很固执的原则——一帧都不留在内存里。",
      "每一帧都有一段很短的生命。页面滚动，Service Worker 请求截图，Offscreen Document 立刻把图片写进 IndexedDB，再回一个 ACK。只有确认这一帧已经落盘，系统才继续下一帧。任何时刻，后台拿着的都只是一张图。",
      "真正麻烦的反而不是截图按钮。Google Docs 和飞书并不一定滚动 window，它们有自己的内部容器。我给候选容器算分：可滚动距离乘上可见面积。最大的那个通常才是正文，旁边的聊天框和工具栏会自然输掉。",
      "最后一屏也会骗人。浏览器会自动限制滚动位置，所以它常常和前一屏重叠一小截。我把内容边界单独记下来，用一个纯函数计算应该裁掉多少；它很不起眼，但有单元测试，因为这种地方一旦错了，三百页之后才发现会很痛苦。",
      "PDF 也不能一次吃下所有图片。Cassie Capture 每一百页生成一个分卷：读一帧、裁一帧、加入当前 PDF、释放引用。满一百页就下载并删除已经使用的帧，再开始下一卷。最后得到的是 part-01-of-05，而不是一个把浏览器拖死的巨大 Canvas。",
      "Manifest V3 会随时终止 Service Worker，Chrome 又限制截图频率。这些限制最初都很烦，但它们逼着我把协调、存储和生成拆开。Content Script 管页面，Service Worker 管节奏，Offscreen Document 管重活。",
      "我以前很容易把约束理解成‘这里做不了’。做完这个项目后，我更愿意把它当成架构的起点。长文档不是因为太长就应该消失在滚动条里；系统只是需要学会，一次认真接住一页。",
      "Cassie Capture 目前已经准备好 v1.2 上架包、商店文案和截图，还在等待真正提交与审核。它不是一个什么都能截的工具，只认真做一件事：把超长网页文档变成可以保存、可以翻阅的 PDF。"
    ], [
      "I often need to save very long web documents: course notes, Feishu docs, and Google Docs that run to three or four hundred pages. Most capture tools work well for a few dozen pages. Past a hundred, the browser may crash or the exported PDF comes out half blank.",
      "I first treated it as a screenshot problem. The real problem was memory. Keeping hundreds of uncompressed frames alive can consume several gigabytes, so Cassie Capture adopted one stubborn rule: never keep the whole page in memory.",
      "Each frame has a short life. The page scrolls, the service worker requests a capture, and the offscreen document immediately persists it to IndexedDB and returns an ACK. Only then does the next frame begin. The background process holds one image, not hundreds.",
      "The capture button was not the hardest part. Google Docs and Feishu often scroll inside their own containers. I score candidates by scrollable distance times visible area; the document tends to win while chat panels and toolbars fall away.",
      "The last viewport is deceptive too. Browsers clamp the final scroll position, creating overlap with the previous frame. A small pure function tracks content boundaries and calculates the crop. It has tests because discovering a seam after page three hundred is a terrible debugging strategy.",
      "A single canvas cannot safely hold five hundred pages, either. Cassie Capture builds one PDF part per hundred pages: read a frame, crop it, append it, release it. Once a part is full, it downloads and its source frames are deleted before the next part begins.",
      "Manifest V3 may terminate the service worker at any time, and Chrome limits capture frequency. Those constraints forced the architecture to become clearer: the content script handles the page, the service worker coordinates, and the offscreen document performs storage and PDF work.",
      "I used to hear a constraint as a reason something could not be done. This project taught me to use it as the first design input. A long document should not disappear because it is long; the system just needs to learn to hold one page carefully at a time.",
      "Cassie Capture now has a v1.2 release package, store copy, and screenshots prepared; submission and review are still ahead. It is not trying to capture everything. It does one job: turn very long web documents into PDFs people can keep and read."
    ]]
  },
  {
    id: "1day",
    cat: "build",
    title: ["我想保留的不是视频，而是一天的感觉", "I want to keep the feeling of a day, not just a video"],
    meta: ["1DAY · 创作笔记", "1DAY · MAKING NOTES"],
    deck: ["记录应该发生在生活里，而不是生活结束之后。", "Recording should happen inside life, not after it ends."],
    body: [[
      "大多数日子不会被记住。不是因为它们不好，是因为没有留下什么。",
      "我不太想拍 vlog。它需要计划、拍摄、剪辑，一打开前置摄像头，人也很容易开始表演。我真正想留下来的，常常只是两秒钟的风、五秒钟的笑声，或者十秒钟一起走回家的路。",
      "所以 1Day 没有先给你一个空白的录像按钮。它给的是一组时刻提示：Wake up、Coffee、Golden hour、Wind down。不同模板不是滤镜，而是不同的叙事顺序。Perfect Day 从日出走到月光，Soft Reset 记录一天怎么慢慢恢复。",
      "这些提示都用稳定的 moment key 保存，而不是直接存显示文字。听起来很像一个很小的工程决定，但它意味着中英文切换时，已经拍下来的生活不会因为翻译改变而坏掉。",
      "所有视频合成都在手机上完成，不需要上传。片段会在两条视频轨道之间交替，用很短的交叉淡入淡出接起来；方向会归一化，竖屏和横屏不会突然打架。模拟器不支持的 Core Animation overlay，则只在真机上启用。",
      "多人模式让我重新想了一遍‘一起记录’是什么。朋友不需要同时在线，也不需要学习一套复杂流程。房间只有一个六位码，同一个人重新录同一天，会更新确定的 CloudKit 记录，而不是制造重复。表情反应也是幂等的。",
      "单人模式不需要账户，也不需要网络。CloudKit 只是可选协作层。我很在意这件事，因为记录生活不应该先要求你把生活交给一个服务器。",
      "做 1Day 的时候，我反复问自己：什么值得被记住？后来答案没有变得更宏大，反而越来越小。咖啡的热度、窗外的光、回家路上耳机里的歌。文字有时候说不清，但两秒钟刚好。",
      "两秒够短，短到你还没来得及表演；也够长，长到几个月以后，你会突然想起那一天。1Day 目前还在 Private Beta。它不是一个更复杂的剪辑器，是一个尽量不打断生活的记忆容器。"
    ], [
      "Most days are forgotten. Not because they were bad, but because nothing stayed.",
      "I do not really want to make vlogs. They require planning, filming, and editing, and the front camera can make ordinary life feel like a performance. What I want to keep is usually smaller: two seconds of wind, five seconds of laughter, or ten seconds of walking home together.",
      "That is why 1Day does not begin with an empty record button. It offers moment prompts such as Wake up, Coffee, Golden hour, and Wind down. The templates are not filters; they are different narrative shapes. Perfect Day moves from sunrise to moonlight. Soft Reset follows a day gradually recovering.",
      "The prompts are stored as stable moment keys rather than display text. It sounds like a tiny engineering choice, but it means switching between Chinese and English never corrupts a memory that has already been recorded.",
      "All video composition happens on the phone. Clips alternate between two tracks with short crossfades, orientation is normalized, and Core Animation overlays that fail in the simulator are enabled only on real devices.",
      "Friend mode made me rethink what recording together should require. People do not need to be online at the same time or learn a complicated workflow. A room has a six-character code, and recording the same day again updates a deterministic CloudKit record instead of creating duplicates. Reactions are idempotent too.",
      "Solo mode needs no account and no network. CloudKit is only an optional collaboration layer. I care about that boundary because recording a life should not begin by asking someone to hand that life to a server.",
      "While building 1Day, I kept asking what deserves to be remembered. The answer became smaller, not grander: the warmth of coffee, the light outside a window, the song playing on the walk home. Words sometimes miss those things, but two seconds can hold them.",
      "Two seconds is short enough that I do not begin performing, and long enough to bring a day back months later. 1Day is currently in private beta. It is not a more complicated editor; it is a memory container designed not to interrupt the life it records."
    ]]
  },
  {
    id: "tabspace",
    cat: "build",
    title: ["Tabspace：把决定权留给用户", "Tabspace: keeping the final say with the user"],
    meta: ["PRODUCT NOTE · 已扩写", "PRODUCT NOTE · EXPANDED"],
    deck: ["AI 可以整理，但不能偷偷替你整理。", "AI can organize, but it should not do so secretly."],
    body: [[
      "我的浏览器长期有六十到一百个标签页。不是每一个都重要，只是关掉任何一个时，我都会想：万一等一下要用呢？",
      "很多整理工具给出的答案是自动分类、自动关闭、自动替你决定。我不太喜欢。混乱当然让人累，但一个工具如果在背后悄悄改变你的工作现场，也会制造另一种不安。",
      "Tabspace 最早只是把标签页按域名放进卡片里。你可以看到 GitHub 开了几个页面、哪些 URL 重复、哪一组可以关掉。去重、分组和关闭都是真实操作，但执行之前，变化先摆在你面前。",
      "后来我把同样的逻辑放进书签整理：搜索、重复检测、批量移动和推荐文件夹都可以做，但破坏性操作必须先预览。‘先预览，再执行’不是为了多一个确认弹窗，而是为了让用户仍然知道自己的东西去了哪里。",
      "Reader Assist 则是另一种整理。它不替你总结文章，而是把当前段落亮起来，让其他内容安静一点。你可以用键盘移动焦点、设置十五分钟计时，也可以把一句话标成重点、概念、行动或疑问。它帮助的是阅读动作，不是假装替你读完。",
      "Manifest V3 的内容安全策略不喜欢现代打包工具的默认输出。为了让 React 页面同时跑在扩展和本地预览里，我做了自定义构建改写，也把 Chrome 的回调 API 集中包装成 Promise。技术细节很多，但它们都服务于一件事：工具要在真实浏览器里稳定工作，而不是只在 demo 里好看。",
      "商店里的 0.1.0 版本完全本地运行。后来仓库加入过可选 AI 分组建议：只发送 tabId、标题、hostname 和当前分组，不发完整 URL 或页面内容，而且必须由用户主动点击。建议回来以后，也还是先看、再 Apply。",
      "这个项目并不是一条很整齐的产品路线。上架以后我做过 Focus Assistant，后来又把它拆掉；当前仓库和商店版本也不是同一个时间切片。以前我会觉得这种反复很难看，现在我更愿意把它留下来——做产品本来就包括删掉自己曾经很认真做过的东西。",
      "Tabspace 教会我的不是‘自动化越多越好’。恰恰相反：AI 可以帮忙看见模式，可以提出建议，但最后那一下，应该由用户自己按。"
    ], [
      "My browser often holds sixty to a hundred tabs. They are not all important. Closing any one of them simply triggers the same thought: what if I need it in five minutes?",
      "Many organization tools answer with automatic grouping, closing, and decision-making. I do not love that. Clutter is tiring, but a tool that silently changes a working environment creates a different kind of anxiety.",
      "Tabspace began by placing tabs into domain cards. I can see how many GitHub pages are open, which URLs repeat, and which group might be safe to close. Deduping, grouping, and closing are real actions, but the change appears before it happens.",
      "I later applied the same rule to bookmarks. Search, duplicate detection, bulk moves, and folder suggestions are useful, but destructive operations must be previewed. Preview before apply is not an extra confirmation dialog; it is how the user continues to know where their things went.",
      "Reader Assist organizes attention instead. It does not pretend to read an article for me. It highlights the current paragraph, quiets the rest of the page, supports keyboard navigation and a fifteen-minute timer, and lets me mark a line as an idea, action, question, or key point.",
      "Manifest V3 content security rules do not cooperate with the default output of modern bundlers. I built a custom output rewrite, supported both Chrome and local preview runtimes, and wrapped callback APIs in promises. The details serve one purpose: the tool must work inside a real browser, not only look convincing in a demo.",
      "The 0.1.0 store release runs locally. A later repository version added optional AI grouping suggestions that send only tab IDs, titles, hostnames, and current group IDs—not full URLs or page content—and only after an explicit user action. Returned suggestions are still reviewed before Apply.",
      "The product history is not a clean line. I built a Focus Assistant after release and later removed it; the repository and store release now represent different moments. I used to think that history looked messy. I now want to keep it visible because building products includes deleting things I once worked hard on.",
      "Tabspace did not teach me that more automation is always better. It taught me the opposite: AI can reveal patterns and make suggestions, but the final click should stay with the user."
    ]]
  },
  {
    "id": "mushroom",
    "cat": "reflection",
    "title": [
      "待机小蘑菇",
      "The Little Idle Mushroom"
    ],
    "meta": [
      "随笔 · 五集重构版",
      "ESSAY · FIVE-EPISODE EDITION"
    ],
    "deck": [
      "一颗长期待机的小蘑菇，怎样停止空转，重新开始行动。",
      "How a little mushroom stuck in idle mode learns to stop spinning and start moving."
    ],
    "body": [
      [
        "## 第一集：先按下去",
        "网申页面终于走到最后一步。",
        "<strong>Step 12 of 12：Upload Resume</strong>",
        "我松了一口气，点开文件夹。",
        "里面躺着一整个简历家族：",
        "<em>Resume_final.pdf</em><br><em>Resume_final_final.pdf</em><br><em>Resume_USE_THIS.pdf</em><br><em>Resume_USE_THIS_REALLY.pdf</em><br><em>Resume_不要用这个.pdf</em><br><em>Resume_真的最终版.pdf</em>",
        "我的手停在鼠标上。",
        "脑内控制室红灯爆闪。",
        "小工头一把拉响警报：“版本管理事故！”",
        "小C抱着一摞尴尬录像带滚进战壕：“传错以后，HR 会不会永远记得我们？”",
        "小E已经打开了一个空白文档：“我建议现在重写一版。做一个有灵魂的简历，点开还会长蘑菇。”",
        "“现在不是长蘑菇的时候！”",
        "我打开一个版本，放大，关掉。又打开一个，搜索 typo，再关掉。",
        "就在这时，页面右上角弹出一行字：",
        "<strong>Session expires in 30 seconds.</strong>",
        "控制室里三个人同时尖叫。",
        "“选最新的！”",
        "“最新的不一定最好！”",
        "“要不趁最后三十秒重新规划人生？”",
        "倒计时往下跳。",
        "<strong>10。9。8。</strong>",
        "我越紧张越想打哈欠。终于，一个巨大的哈欠把意识从现实里拽了出去——下一秒，我从控制室天花板上掉下来，一屁股坐在三个人中间。",
        "全场安静。",
        "小工头第一个站直：“老板！我们正在抢救您的职业生涯！”",
        "他递给我一本皱巴巴的手册。封面是我的笔迹：",
        "> <strong>《绝对不能搞砸的人生应急预案》</strong>",
        "我翻开第一页，只写了一条：",
        "> 不能出错。出错会引发连锁坍塌。",
        "“所以，”我抬头看着他们，“你们每天这么忙，是因为把每一个错误都当成拆迁？”",
        "小C小声说：“我们只是想让你安全一点。”",
        "我拿起笔，把那句话划掉。",
        "> <strong>做错了，不算塌房，算待修。</strong>",
        "“传错简历怎么办？”小工头问。",
        "“重新投，补邮件，下次改好文件名。”",
        "“尴尬怎么办？”小C问。",
        "“先尴尬。尴尬完继续。”",
        "“奶茶怎么办？”小E问。",
        "“先闭麦。”",
        "现实里的倒计时还剩三秒。",
        "我选中 <em>Resume_USE_THIS_REALLY.pdf</em>，上传，点击 <strong>Submit</strong>。",
        "页面转了一圈。",
        "<strong>Application submitted.</strong>",
        "控制室没有烟花。小工头摘下安全帽，小C从指缝里往外看。",
        "“系统没崩。”小工头说。",
        "“我们也没死。”小C说。",
        "小E立刻举手：“那现在可以喝奶茶了吗？”",
        "我站起来，走进厨房，接了一杯温水。",
        "“先喝水。”",
        "小E震惊：“这是什么冷酷的世界。”",
        "## 第二集：麻辣香锅公司侥幸存活",
        "上周，我看了一个美食综艺，叫《一饭封神》。",
        "看着看着，我的脑子就自己开了一家公司。",
        "一开始，好像是一家毛血旺公司。",
        "过了一会儿，又变成了麻辣香锅公司。为什么突然更换主营业务，没有人知道。总之，这家公司经营得很艰难，眼看就快撑不下去了。",
        "就在这个时候——",
        "牛奶降价了。",
        "于是，我的麻辣香锅公司侥幸存活。",
        "梦进行到这里，我突然清醒了一下。",
        "等等。",
        "牛奶降价，和麻辣香锅公司活下来，到底有什么关系？",
        "我停下来，认真回看了整段剧情。",
        "毛血旺。麻辣香锅。公司。牛奶降价。侥幸存活。",
        "这他妈到底是个什么故事？",
        "控制室里，小工头已经把紧急调查报告投到了大屏上：",
        "> <strong>事故名称：麻辣香锅公司异常存活事件</strong><br><strong>主营业务：不明确</strong><br><strong>盈利模式：不明确</strong><br><strong>牛奶价格与公司存亡的关系：完全不明确</strong>",
        "小C抱着脑部档案，脸色苍白：“我们的脑子是不是有点大病？”",
        "小E很不服气：“也可能这家公司同时卖奶茶。”",
        "“没有这个设定。”小工头说。",
        "“现在有了。”",
        "“不允许事后补设定！”",
        "三个人围着那份报告吵了起来，试图从一段根本没有逻辑的梦里，找出一条完整的商业链路。",
        "我看了一会儿，决定放弃调查。",
        "有些念头可能真的没有什么意义。只是刚刚看进去的东西，被脑子随手倒进一口锅里，炒了炒，就端上来了。",
        "闻着挺香。",
        "逻辑没熟。",
        "小工头仍然无法接受：“那这家公司现在怎么办？”",
        "“先让它活着吧。”",
        "“靠什么活？”",
        "“牛奶不是降价了吗？”",
        "## 第三集：地图只画了一条路",
        "控制室的墙上，一直挂着一张很大的地图。",
        "地图上只有一条红色路线：",
        "> <strong>找到工作 → 人生恢复正常</strong>",
        "那条路被描得很粗，几乎占满整张纸。小工头每天站在下面调度，小C负责标记沿途所有可能失败的地方，小E偶尔试图往旁边画一条岔路，都会被小工头立刻擦掉。",
        "“这条跟当前目标无关。”他说。",
        "我盯着这张地图太久了。",
        "久到后来，我真的以为，世界上只有这一条路。只要还没走通，其他事情就都不应该开始；只要还没得到它，我的人生就还停在原地。",
        "回国以后，生活里忽然冒出了很多和这张地图无关的事情。",
        "我去了韩国，决定做之前纠结了很久的全飞秒。两个小时内，检查、复查、手术全部做完。院长长得很像梁朝伟，我还用破碎的韩语夸他帅。",
        "我在那里认识了几个很聊得来的中国小姐姐。手术后，三个人坐在一起吃饭：两个戴着墨镜，睁不开眼，另一个脸上还敷着麻药，刚好能拼出一张完整的脸。",
        "控制室里，小工头看着行程记录，很困惑：“这件事对求职有什么帮助？”",
        "“没有。”我说。",
        "“那为什么要做？”",
        "“因为我想做。”",
        "他说不出话了。",
        "我开始发现，自己能做的事情比原来以为的多。它们不需要先证明对某个目标有帮助，也不需要排在“人生恢复正常”之后。",
        "我回到控制室，把墙上那张地图摘了下来。",
        "翻到背面，才看见角落里印着一行很小的字：",
        "> <strong>紧急疏散示意图</strong>",
        "原来它从来都不是世界地图。",
        "它只是在我很害怕的时候，为我画出了一个最近的出口。控制室拿着它用了太久，最后连自己也忘了，出口外面还有路，墙的另一边也还有房间。",
        "我重新摊开一张纸。",
        "找工作仍然在上面，但不再占满整页。周围暂时还是空白，我也不知道以后会画出什么。",
        "小工头拿着笔问：“那哪一条才是正确答案？”",
        "“没有固定答案。”",
        "“那我们必须想要什么？”",
        "我想了想。",
        "“没有什么是必须想要的。”",
        "我可以认真走一条路，也可以发现不喜欢以后再转弯。地图不是命令，它只是让我看见：这里有路。",
        "至于走哪一条——",
        "尽量选我真的想走的。",
        "## 第四集：不等心情开机",
        "最近，我认识了一些无时无刻不在工作的人。",
        "最让我意外的，不是他们能工作多久，而是他们好像并不需要先举行一场仪式。",
        "事情来了，就处理。做完一件，再做下一件。",
        "工作就是工作。",
        "控制室却不是这样。",
        "每天早上，小工头都抱着一张表守在门口：",
        "> <strong>工作状态准入检测</strong>",
        "“昨晚睡够了吗？”",
        "“没有。”",
        "“心情稳定吗？”",
        "“也没有。”",
        "“对今天的任务有热情吗？”",
        "我想了想：“现在只对重新躺下有热情。”",
        "小工头沉重地盖下红章：<strong>未通过。</strong>",
        "于是大家决定，先把心情调整好，再开始工作。",
        "小C搬出情绪档案，准备调查我为什么抗拒。小E打开十几个页面，搜索“如何在三分钟内恢复能量”。小工头坐下来，开始制定《进入工作状态前的准备工作清单》。",
        "他们忙得不可开交。",
        "只有工作没有开始。",
        "我原来总觉得，要先不焦虑、不内耗、想明白，最好还能产生一点期待，才可以开始做事。",
        "可心情很像一台永远差百分之三才更新完成的电脑。你盯着它，它就一直转圈。",
        "“最佳状态什么时候到？”我问。",
        "小工头翻了翻表格：“没有预计到达时间。”",
        "“那把门拆了。”",
        "“可是状态检测——”",
        "“状态可以检测，不能拿来当门禁。”",
        "我拿过他的表格，在最下面加了一行：",
        "> <strong>心情未就绪，不影响文件打开。</strong>",
        "然后我坐下来，打开要做的事。",
        "焦虑没有消失，动力也没有突然出现。小C照常抱着档案坐在二号位，小E还在旁边研究那套晨间仪式。",
        "但屏幕上的光标开始往前走。",
        "我好像到最近才重新意识到，工作很重要。很多能力不是等我准备好以后才长出来的，是一遍遍做的时候长出来的。",
        "累了就休息，方向错了就调整。但休息就是休息，调整就是调整，不再把它们变成一道永远过不完的前置流程。",
        "与其花很久说服自己心甘情愿地工作，不如就工作。",
        "就是工作。",
        "小工头重新画了一张流程图。",
        "原来的版本是：",
        "> 调整心情 → 找到动力 → 进入最佳状态 → 开始工作",
        "他把整张图划掉，只留下两个格子：",
        "> 打开 → 做",
        "小E很不满意：“这也太不浪漫了。”",
        "“可以再加一个格子。”我说。",
        "她眼睛一亮：“做完奖励奶茶？”",
        "“做完检查下一步。”",
        "小E把笔放下：“比不浪漫还不浪漫。”",
        "第二天早上，我还是有点困，也没有突然热爱上所有任务。",
        "小工头摸了摸口袋里的准入表格，又把它放了回去。",
        "我坐下来，打开文件。",
        "小C问：“今天不开状态审核会吗？”",
        "“不开。”",
        "“那我们什么时候开始？”",
        "我的手已经放在键盘上。",
        "“已经开始了。”",
        "## 第五集：把脑子放回身体里",
        "最近，我开始看一些和礼仪有关的书。",
        "也是在这个时候，我想起那天去寺里，自己很难把注意力留在手上的感觉。",
        "手明明在这里，脑子却一会儿想这件事，一会儿跳到另一件事。身体已经开始做了，思想还在外面四处乱跑。",
        "控制室里，情况更加严重。",
        "小E同时放飞了二十几个念头。有的飞向昨天，有的飞向明天，还有几个没有明确目的地，只是在天花板附近高速盘旋。",
        "小工头追着它们逐个登记。",
        "小C抱着档案问：“刚才那件事是不是还没有想完？”",
        "大屏正中央，手部操作画面已经卡住很久。",
        "“停。”我说。",
        "三个人一起看向我。",
        "“先把脑子放回手上。”",
        "我开始想，专注也许不只是要求自己“不要乱想”。这个指令太空了，脑子听完以后，还是不知道应该去哪里。",
        "它需要一个可以落下来的地方。",
        "如果我正在落笔，就看着自己的手：下一笔落在哪里，怎样把它落稳。",
        "如果我正在坐着，就把坐姿坐好。",
        "如果我正在站着，就把站姿站好。",
        "不再任由一个想法把下一个想法拖出来。先给身体一个明确的任务，让思想回来和它做同一件事。",
        "小E指着天上那些还在飞的念头：“那它们怎么办？”",
        "“能变成行动的，就告诉我现在可以做什么。”",
        "“暂时不能的呢？”",
        "“排队。不要占着整个屏幕。”",
        "小工头立刻搬来一只箱子，上面写着：",
        "> <strong>以后再想，不等于现在要想</strong>",
        "我不需要把脑子彻底清空。它可以有声音，也可以冒出一些奇怪的东西——毕竟它连靠牛奶降价存活的麻辣香锅公司都想得出来。",
        "但如果我想把一件事做好，脑子就不能永远只负责发散，身体也不能永远等在那里。",
        "思想要落到动作上。",
        "坐，就坐好。",
        "站，就站好。",
        "下一次落笔的时候，我想先试着只做一件事：看着自己的手，把这一笔稳稳地落下去。",
        "控制室的大屏上，二十几个窗口慢慢退到后台。",
        "手部画面重新回到正中央。",
        "这一次，脑子和手在同一个地方。"
      ],
      [
        "## Episode One: Just Click It",
        "The application finally reached its last step.",
        "<strong>Step 12 of 12: Upload Resume</strong>",
        "I exhaled and opened the folder.",
        "An entire résumé family was waiting inside:",
        "<em>Resume_final.pdf</em><br><em>Resume_final_final.pdf</em><br><em>Resume_USE_THIS.pdf</em><br><em>Resume_USE_THIS_REALLY.pdf</em><br><em>Resume_DO_NOT_USE.pdf</em><br><em>Resume_ACTUAL_FINAL.pdf</em>",
        "My hand froze over the mouse.",
        "Red lights erupted in the control room inside my head.",
        "The foreman yanked the alarm. “Version-control incident!”",
        "Little C rolled into a trench clutching a stack of embarrassing old tapes. “If we upload the wrong one, will HR remember us forever?”",
        "Little E had already opened a blank document. “I suggest we rewrite it now. Something with soul. Maybe mushrooms grow when you open it.”",
        "“This is not the time to grow mushrooms!”",
        "I opened one version, zoomed in, and closed it. I opened another, searched for typos, and closed that too.",
        "Then a line appeared in the top-right corner:",
        "<strong>Session expires in 30 seconds.</strong>",
        "All three people in the control room screamed.",
        "“Choose the newest one!”",
        "“Newest does not mean best!”",
        "“Should we use the last thirty seconds to redesign our entire life?”",
        "The countdown continued.",
        "<strong>10. 9. 8.</strong>",
        "The more nervous I get, the more I yawn. One enormous yawn finally pulled my consciousness out of reality. A second later, I fell through the control-room ceiling and landed between the three of them.",
        "Silence.",
        "The foreman snapped to attention. “Boss! We are actively rescuing your career!”",
        "He handed me a crumpled manual. The title was in my handwriting:",
        "> <strong>The Emergency Plan for a Life That Absolutely Must Not Go Wrong</strong>",
        "I opened to the first page. It contained one rule:",
        "> No mistakes. One mistake will trigger a total collapse.",
        "“So,” I said, looking at them, “you stay this busy because every mistake becomes a demolition order?”",
        "Little C lowered his voice. “We only wanted to keep you safe.”",
        "I picked up a pen and crossed out the rule.",
        "> <strong>A mistake is not a collapse. It is a repair ticket.</strong>",
        "“What if we send the wrong résumé?” the foreman asked.",
        "“Apply again. Send a correction. Name the file properly next time.”",
        "“What about the embarrassment?” Little C asked.",
        "“Be embarrassed. Then keep going.”",
        "“What about milk tea?” Little E asked.",
        "“Mute yourself for a moment.”",
        "The real countdown had three seconds left.",
        "I selected <em>Resume_USE_THIS_REALLY.pdf</em>, uploaded it, and clicked <strong>Submit</strong>.",
        "The page spun once.",
        "<strong>Application submitted.</strong>",
        "There were no fireworks in the control room. The foreman took off his hard hat. Little C peeked through his fingers.",
        "“The system did not crash,” the foreman said.",
        "“We did not die either,” Little C said.",
        "Little E raised a hand immediately. “Can we have milk tea now?”",
        "I stood up, walked into the kitchen, and poured a cup of warm water.",
        "“Water first.”",
        "Little E stared at me. “What kind of cruel world is this?”",
        "## Episode Two: The Mala Xiang Guo Company Survives Somehow",
        "Last week, I watched a food competition show called <em>Yi Fan Feng Shen</em>.",
        "Somewhere along the way, my brain started a company by itself.",
        "At first, it seemed to be a maoxuewang company.",
        "Then it became a mala xiang guo company. No one knows why the business suddenly changed its main product. In any case, the company was struggling and about to go under.",
        "At that exact moment—",
        "milk prices fell.",
        "And so my mala xiang guo company survived by sheer luck.",
        "Halfway through this dream, I suddenly became lucid.",
        "Wait.",
        "What did cheaper milk have to do with the survival of a mala xiang guo company?",
        "I stopped and reviewed the plot carefully.",
        "Maoxuewang. Mala xiang guo. A company. Cheaper milk. Miraculous survival.",
        "What the hell kind of story was this?",
        "In the control room, the foreman had already projected an emergency investigation report onto the main screen:",
        "> <strong>Incident: Unexplained Survival of the Mala Xiang Guo Company</strong><br><strong>Core business: Unknown</strong><br><strong>Revenue model: Unknown</strong><br><strong>Connection between milk prices and corporate survival: Entirely unknown</strong>",
        "Little C held the brain archive with a pale face. “Is there something seriously wrong with our brain?”",
        "Little E objected. “Maybe the company also sells milk tea.”",
        "“That was not part of the story,” the foreman said.",
        "“It is now.”",
        "“No retroactive world-building!”",
        "The three of them crowded around the report, trying to recover a complete business model from a dream with no logic at all.",
        "I watched for a while, then abandoned the investigation.",
        "Some thoughts may genuinely mean nothing. The brain takes whatever just went in, dumps it into a wok, gives it a few tosses, and serves it.",
        "Smells great.",
        "Logic undercooked.",
        "The foreman still could not accept this. “What happens to the company now?”",
        "“Let it live for a while.”",
        "“On what?”",
        "“Milk is cheaper now, isn't it?”",
        "## Episode Three: The Map With Only One Road",
        "A large map had always hung on the control-room wall.",
        "It showed one red route:",
        "> <strong>Get a job → Life returns to normal</strong>",
        "The line was drawn so thick that it filled almost the entire page. The foreman scheduled everything beneath it. Little C marked every place where the route might fail. Whenever Little E tried to draw a side road, the foreman erased it at once.",
        "“Not relevant to the current objective,” he said.",
        "I stared at that map for too long.",
        "Eventually, I really believed the world contained only that road. Until I finished it, nothing else should begin. Until I got the answer, my life had not moved.",
        "After I returned to China, life began producing things that had nothing to do with the map.",
        "I went to Korea and finally chose the SMILE Pro procedure I had debated for a long time. The examination, follow-up, and surgery were finished within two hours. The director looked like Tony Leung, and I used my broken Korean to tell him he was handsome.",
        "I met a few Chinese women there, and we got along immediately. After surgery, three of us ate together: two wearing sunglasses because they could not open their eyes, and one with anesthetic still on her face. Together, we could just about assemble one complete face.",
        "The foreman studied the itinerary in confusion. “How does this help the job search?”",
        "“It doesn't,” I said.",
        "“Then why do it?”",
        "“Because I wanted to.”",
        "He had no reply.",
        "I began to notice that I could do more than I had imagined. Those things did not have to prove their usefulness to one goal, and they did not have to wait until after “life returns to normal.”",
        "I went back to the control room and took the map off the wall.",
        "On the back, in tiny print, I found a label:",
        "> <strong>Emergency evacuation diagram</strong>",
        "It had never been a map of the world.",
        "It had only shown me the nearest exit when I was scared. The control room used it for so long that everyone forgot there were roads outside the exit and more rooms beyond the wall.",
        "I spread out a new sheet of paper.",
        "The job search was still on it, but it no longer filled the page. The space around it remained blank. I did not yet know what would be drawn there.",
        "The foreman held up his pen. “Which road is the correct answer?”",
        "“There is no fixed answer.”",
        "“Then what are we required to want?”",
        "I thought for a moment.",
        "“Nothing is automatically required.”",
        "I can take one road seriously and still turn when I discover I do not like it. A map is not an order. It only shows me that roads exist.",
        "As for which one to take—",
        "I will try to choose the one I actually want.",
        "## Episode Four: Do Not Wait for the Mood to Boot",
        "Recently, I met a few people who seem to be working all the time.",
        "What surprised me was not how long they worked. It was that they did not seem to need a ceremony before starting.",
        "Something arrives; they handle it. They finish one thing and begin the next.",
        "Work is work.",
        "The control room worked differently.",
        "Every morning, the foreman guarded the door with a form:",
        "> <strong>Work Readiness Admission Test</strong>",
        "“Did you sleep enough?”",
        "“No.”",
        "“Is your mood stable?”",
        "“Also no.”",
        "“Do you feel enthusiastic about today's tasks?”",
        "I thought about it. “Right now, I am only enthusiastic about lying down again.”",
        "The foreman stamped the form: <strong>FAILED.</strong>",
        "So everyone decided to fix my mood before work could begin.",
        "Little C brought out the emotion archives to investigate my resistance. Little E opened a dozen pages and searched “how to restore energy in three minutes.” The foreman sat down to draft a Pre-Work Preparation Checklist.",
        "They were extremely busy.",
        "Only the work had not started.",
        "I used to believe I had to stop worrying, stop spiraling, understand everything, and preferably feel a little hope before I could begin.",
        "But mood is like a computer update forever stuck at ninety-seven percent. If you keep watching, it keeps spinning.",
        "“When does the ideal state arrive?” I asked.",
        "The foreman checked his form. “No estimated arrival time.”",
        "“Then take down the door.”",
        "“But the readiness test—”",
        "“State can be observed. It cannot become an access gate.”",
        "I took the form and added one line at the bottom:",
        "> <strong>Mood not ready. File may still open.</strong>",
        "Then I sat down and opened the work in front of me.",
        "The anxiety did not disappear. Motivation did not suddenly arrive. Little C sat in seat two with the archives. Little E continued researching that morning ritual.",
        "But the cursor began to move.",
        "Only recently did I remember that work matters. Many abilities do not appear after I become ready. They grow through doing the thing again and again.",
        "If I am tired, I rest. If the direction is wrong, I adjust it. But rest is rest, and adjustment is adjustment. They do not need to become an entrance ritual with no end.",
        "Instead of spending hours persuading myself to want the work, I can work.",
        "Just work.",
        "The foreman drew a new flowchart.",
        "The old one said:",
        "> Fix mood → Find motivation → Reach ideal state → Begin work",
        "He crossed out the whole diagram and left two boxes:",
        "> Open → Do",
        "Little E frowned. “That is extremely unromantic.”",
        "“We can add one more box,” I said.",
        "Her eyes lit up. “Finish, then milk tea?”",
        "“Finish, then check the next step.”",
        "Little E put down the pen. “That is worse than unromantic.”",
        "The next morning, I was still sleepy. I had not fallen in love with every task overnight.",
        "The foreman touched the admission form in his pocket, then left it there.",
        "I sat down and opened the file.",
        "Little C asked, “No readiness review today?”",
        "“No.”",
        "“Then when do we start?”",
        "My hands were already on the keyboard.",
        "“We already did.”",
        "## Episode Five: Put the Mind Back in the Body",
        "Recently, I started reading books about etiquette.",
        "Around the same time, I remembered how hard it had been at the temple to keep my attention on my own hands.",
        "My hands were here, but my mind jumped from one subject to another. The body had begun the task. Thought was still running around somewhere else.",
        "Inside the control room, the situation was worse.",
        "Little E released more than twenty thoughts at once. Some flew toward yesterday, some toward tomorrow, and several had no destination at all. They simply circled the ceiling at high speed.",
        "The foreman chased them and tried to register each one.",
        "Little C held up the archives. “Did we ever finish thinking about that earlier thing?”",
        "In the center of the main screen, the camera feed from my hands had been frozen for a long time.",
        "“Stop,” I said.",
        "All three looked at me.",
        "“Put the mind back in the hands.”",
        "I began to think that focus might require more than telling myself not to wander. That instruction is too empty. The brain hears it and still has no idea where to go.",
        "It needs somewhere to land.",
        "If I am making a mark, I can watch my hand: where should the next stroke go, and how can I place it steadily?",
        "If I am sitting, I can sit well.",
        "If I am standing, I can stand well.",
        "Instead of letting one thought drag out the next, I can give the body one clear task and ask the mind to return and do the same thing.",
        "Little E pointed at the thoughts still flying overhead. “What happens to those?”",
        "“If one can become an action, tell me what I can do now.”",
        "“And if it cannot?”",
        "“It queues. It does not get the whole screen.”",
        "The foreman immediately carried in a box labeled:",
        "> <strong>Think about it later does not mean think about it now</strong>",
        "I do not need to empty my head completely. It can make noise and produce strange things. This is, after all, the brain that kept a mala xiang guo company alive by lowering the price of milk.",
        "But if I want to do something well, the mind cannot spend forever generating possibilities while the body waits.",
        "Thought has to land in action.",
        "Sit, and sit well.",
        "Stand, and stand well.",
        "The next time I make a mark, I want to try one thing first: watch my hand and place that stroke steadily.",
        "On the control-room screen, more than twenty windows slowly moved into the background.",
        "The camera feed from my hands returned to the center.",
        "This time, my mind and my hands were in the same place."
      ]
    ]
  },
  {
    id: "route",
    cat: "life",
    title: ["从哈密到 San Jose：一路把自己重新搭起来", "From Hami to San Jose: rebuilding myself along the way"],
    meta: ["LIFE ARCHIVE · 已扩写", "LIFE ARCHIVE · EXPANDED"],
    deck: ["我不是一路规划着来到这里的，只是每到一个阶段，都决定再往前走一点。", "I did not plan the whole route here. At each stage, I chose to move a little farther."],
    body: [[
      "我不是一路规划着来到这里的。如果十八岁的时候有人把哈密、上海、杭州和 San Jose 连成一条线给我看，我大概也不会相信。很多决定当时没有一个很漂亮的解释，只是觉得：要不再往前走一点。",
      "我在哈密长大。风很大，天很蓝，日子也慢。小时候我会在网上学修手机、折纸，也给陌生人做动态签名。那时候当然没有人把这些叫作‘产品意识’或者‘工程兴趣’，我只是天然觉得东西可以拆开，也可以重新做一遍。",
      "十八岁以后去了上海，在上财读国际会计，后来进德勤生命科学与医疗组。会计没有成为我的终点，但审计留下了很顽固的习惯：这个数从哪里来？为什么应该相信它？材料再乱，也要找到一条能复核的证据链。",
      "我写第一行 Python 的动机也没有多高尚，只是想少加一点班。后来自动化总账映射、异常检测，再后来做出一个别的团队也愿意继续用的工具。不是先决定转行再开始写代码，而是先解决了一个眼前的问题，门才开了一点。",
      "杭州是履历里最难用一句话讲清楚的部分。我注册公司、开过店、参加创业比赛，也把一些想法做成真的能打开的产品。那段时间并不稳定，我也没有突然想明白人生，只是把能推的门都推了一遍。",
      "我原来以为自己在不断换方向。后来才发现，行业确实在换，但我总会绕回同一批问题：人为什么会卡住？工具能不能让一个复杂动作变得更清楚？我真正喜欢的，是把问题拆开，再做出一个可以被使用的东西。",
      "2025 年到了 San Jose。在 Smith-Kettlewell 的 YouDescribe 项目里，我参与了 30 人研究；新的工作流把人工撰写时间缩短了 64%。这段经历第一次让我看见，技术不是简历上的新标签，它真的可以改变一个人完成任务的方式。",
      "现在我在 Northeastern 读人工智能硕士，补以前没有系统学过的计算机基础，也继续做自己的 app。来这里不是为了把会计和审计重新包装成技术故事，而是承认基础不够，然后从底下重新学一遍。",
      "这四个地方不是履历上的四个点。哈密给了我拆开看看的习惯，上海给了我商业和证据，杭州让我开始造东西，San Jose 让我重新打地基。我说不清下一站在哪里，但现在我不再要求整条路先有答案。环境对了，人会长出原来想不到的部分。"
    ], [
      "I did not plan the route that brought me here. If someone had connected Hami, Shanghai, Hangzhou, and San Jose on a map when I was eighteen, I probably would not have believed it. Many choices had no elegant explanation at the time. I simply wondered if I should move a little farther.",
      "I grew up in Hami, where the wind is strong, the sky is blue, and days move slowly. I learned phone repair and origami online and made animated forum signatures for strangers. No one called that product instinct or engineering interest. I just believed things could be opened and made again.",
      "At eighteen I moved to Shanghai to study international accounting at SUFE, then joined Deloitte's Life Sciences and Health Care practice. Accounting was not the destination, but audit left a stubborn habit: where did this number come from, and why should anyone trust it? Messy material still needs a traceable evidence chain.",
      "My reason for writing the first line of Python was not noble. I wanted less overtime. General-ledger mapping led to anomaly checks, and eventually to a tool another team wanted to keep using. I did not decide on a career change and then begin coding. I solved an immediate problem, and a door opened slightly.",
      "Hangzhou is the hardest chapter to summarize on a résumé. I registered a company, opened a store, entered startup competitions, and turned a few ideas into products that could actually be opened. It was not stable, and I did not suddenly understand my life. I simply pushed every door I could find.",
      "I used to think I kept changing direction. Later I noticed that the industries changed while the questions did not. Why do people get stuck? Can a tool make a complicated action clearer? What I enjoy is taking a problem apart and building something another person can use.",
      "In 2025 I arrived in San Jose and worked on YouDescribe at Smith-Kettlewell. I participated in a thirty-person study, and the new workflow reduced manual writing time by 64 percent. It was the first time I saw technology not as a new label for my résumé, but as a real change in how someone completes a task.",
      "I now study artificial intelligence at Northeastern, rebuilding computer science foundations I had never learned systematically while continuing to deepen my own apps. I did not come here to repackage accounting and audit as a technology story. I came to admit what I did not know and learn it from the bottom.",
      "These places are not four résumé points. Hami gave me the habit of opening things up. Shanghai gave me business and evidence. Hangzhou made me start building. San Jose made me rebuild the foundation. I do not know the next stop yet, but I no longer need the entire road to explain itself in advance."
    ]]
  }
];
