// Generates en/index.html from index.html.
//
// Why this exists: en/index.html used to be a symlink to ../index.html, so both
// routes shipped byte-identical Chinese <head> markup. studio.js swapped the
// title and description at runtime, which is invisible to crawlers and to every
// social-preview scraper — sharing liangyue.site/en/ produced a Chinese card.
//
// Everything except the <head> metadata is copied verbatim, so the English route
// can never drift from the Chinese one. The sibling symlinks (studio.css,
// studio.js, articles.js, assets, design-system) stay in place, which is what
// keeps the relative asset paths inside the copied markup resolving correctly.
//
// Run after editing the <head> of index.html:  node scripts/build-en.mjs

import { readFileSync, writeFileSync, rmSync, existsSync, lstatSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';

const root = join(dirname(fileURLToPath(import.meta.url)), '..');
const source = join(root, 'index.html');
const target = join(root, 'en', 'index.html');

const EN = {
  title: 'Yue(Cassie) Liang · AI student and independent builder',
  description:
    'Yue(Cassie) Liang is an AI master’s student and independent builder with ' +
    'experience in product operations, product management, business analysis, and audit.',
  ogDescription:
    'Explore Yue(Cassie) Liang’s projects, experience, and writing across AI, product, ' +
    'business analysis, and audit.'
};

// Each rule must match exactly once. A silent no-op here would ship a Chinese
// <head> on the English route, which is the whole bug this script exists to fix.
const rules = [
  ['<html lang="zh-CN">', '<html lang="en">'],
  [
    /<meta name="description" content="[^"]*">/,
    `<meta name="description" content="${EN.description}">`
  ],
  [
    /<meta property="og:title" content="[^"]*">/,
    `<meta property="og:title" content="${EN.title}">`
  ],
  [
    /<meta property="og:description" content="[^"]*">/,
    `<meta property="og:description" content="${EN.ogDescription}">`
  ],
  ['<meta property="og:locale" content="zh_CN">', '<meta property="og:locale" content="en">'],
  ['<meta property="og:url" content="https://liangyue.site/">',
   '<meta property="og:url" content="https://liangyue.site/en/">'],
  ['<link rel="canonical" href="https://liangyue.site/">',
   '<link rel="canonical" href="https://liangyue.site/en/">'],
  [/<title>[^<]*<\/title>/, `<title>${EN.title}</title>`]
];

let html = readFileSync(source, 'utf8');

for (const [pattern, replacement] of rules) {
  const before = html;
  html = html.replace(pattern, replacement);
  if (html === before) {
    console.error(`build-en: pattern not found in index.html -> ${pattern}`);
    process.exit(1);
  }
}

html = html.replace(
  '<head>',
  '<head>\n  <!-- Generated by scripts/build-en.mjs from index.html. Do not edit by hand. -->'
);

if (existsSync(target) || lstatSyncSafe(target)) {
  rmSync(target, { force: true });
}

writeFileSync(target, html);
console.log(`build-en: wrote ${target} (${html.length} bytes)`);

function lstatSyncSafe(path) {
  try {
    return lstatSync(path);
  } catch {
    return null;
  }
}
