import {t} from './i18n';

export type Project = { id:string; name:string; category:string; status:string; description:string; story:string; role:string; decision:string; url:string; source:string; accent:string };
export const projects: Project[] = [
  {id:'mindbridge',name:'MindBridge',category:'AI · MEMORY',status:'可体验 Demo',description:'让 AI 记住你说过的话，也说清楚记忆从哪来。',story:'把个人记忆与可追溯的来源联系起来。可以通过固定合成数据的演示，体验这套记忆工作流。',role:'从记忆模型、检索逻辑到可追溯界面，独立完成产品设计和实现。',decision:'每条召回结果都带回来源；证据不够时，不让模型装作记得。',url:'https://mindbridge.liangyue.site/interview-demo/zh',source:'https://github.com/cassieliang6709/mindbridge',accent:'#dee6da'},
  {id:'1day',name:'1Day',category:'iOS · VIDEO',status:'App Store · v1.1',description:t('几个短暂的瞬间，留住这一天。','A few short moments that keep the whole day.'),story:'记录 2、5 或 10 秒的片段，在设备端拼成短片。通过邀请码，也可以和朋友共同拍摄同一天。',role:'独立完成产品构思、交互设计、SwiftUI 开发、视频合成和发布。',decision:'单人记录完全留在设备上，只有一起拍摄时才启用同步。',url:'https://apps.apple.com/app/id6794565199',source:'https://github.com/cassieliang6709/1day-ios',accent:'#f0ddc6'},
  {id:'tabspace',name:'Tabspace',category:'CHROME · PRODUCTIVITY',status:t('已上架','Live on Chrome Web Store'),description:t('把散乱的标签页，收进一个工作台。','Gather scattered tabs into one workspace.'),story:'从自己浏览器里不断增加的标签页开始，做一个可以预览、整理和重新找到网页的地方。',role:'负责浏览器扩展的产品、交互与前端实现，并完成商店发布。',decision:'先让人预览整理结果，点击确认以后才真正移动或关闭标签页。',url:'https://cassieliang6709.github.io/tabspace-site/',source:'https://github.com/cassieliang6709/tabspace-newtab',accent:'#dce4ef'},
  {id:'vance',name:'Vance',category:'iOS · FITNESS',status:'可体验 Demo',description:'能一起调整训练计划的 AI 健身搭子。',story:'探索对话如何进入实际训练流程，而不只是给出一段建议。',role:'完成训练流程、对话体验和 iOS 原型。',decision:'AI 给出调整理由，但训练者保留最后决定。',url:'https://fitness-coach-demo.pages.dev',source:'https://github.com/cassieliang6709/fitness-coach-ios',accent:'#e5e2d5'},
  {id:'corpcheck',name:'CorpCheck',category:'AI · RESEARCH',status:'可体验 Demo',description:'查财报，也检查答案有没有证据。',story:'证据不够时，明确告诉你查不到。把可信度放在一个听起来完整的回答之前。',role:'设计检索、证据展示和答案核查流程。',decision:'把“没有足够证据”当成一个有效结果，而不是失败状态。',url:'https://corpcheck.liangyue.site',source:'https://github.com/cassieliang6709/corpcheck',accent:'#eadfdc'},
  {id:'capture',name:'Cassie Capture',category:'BROWSER · UTILITY',status:'发布包已准备',description:'为长文档网页做的长截图工具。',story:'来自截图崩溃和导出空白的困扰。尝试让长内容的保存过程更可靠。',role:'独立实现滚动容器识别、分帧写入、裁切和 PDF 分卷。',decision:'任何时候只让一张截图留在内存里，先保证三百页也能完成。',url:'https://github.com/cassieliang6709/cassie-capture/releases',source:'https://github.com/cassieliang6709/cassie-capture',accent:'#e5e4df'}
];
